### ISSUE TITLE
dbatools not working in sql version 2014

### ISSUE THREAD

**Issue by abhishekrnair** [dataplat/dbatools#8217]
### Verified issue does not already exist?

Yes

### What error did you receive?

PS C:\Users\Administrator> Get-DbaDatabase -SqlInstance localhost
WARNING: [12:21:15][Get-DbaDatabase] Failure | Error connecting to [localhost]: Method not found: '!!0[] System.Array.Empty()'.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Get-DbaDatabase -SqlInstance localhost

### Other details or mentions

**

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      4.0                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                   
CLRVersion                     4.0.30319.36627                                                                                                                           
BuildVersion                   6.3.9600.19170                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                                      
PSRemotingProtocolVersion      2.2 

### SQL Server Edition and Build number

Microsoft SQL Server 2014 (SP3-CU4-GDR) (KB4583462) - 12.0.6433.1 (X64) 
	Oct 31 2020 02:54:45 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: )

### .NET Framework Version

Unable to find type [System.Runtime.InteropServices.RuntimeInformation]. Make sure that the assembly that contains this type is loaded.

**Comment by ACALVETT** [comment]
I see you get an error returning the .NET Framework Version as well which suggests a problem on your machine.

What do you get if you run.
```
gci 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -recurse | gp -name Version -EA 0 | where { $_.PSChildName -match '^(?!S)\p{L}'} | select PSChildName, Version
```
Have you tried running the command from another host?

**Comment by abhishekrnair** [comment]
PSChildName                                                                          Version                                                                             
-----------                                                                          -------                                                                             
v2.0.50727                                                                           2.0.50727.4927                                                                      
v3.0                                                                                 3.0.30729.4926                                                                      
Windows Communication Foundation                                                     3.0.4506.4926                                                                       
Windows Presentation Foundation                                                      3.0.6920.4902                                                                       
v3.5                                                                                 3.5.30729.4926                                                                      
Client                                                                               4.5.51650                                                                           
Full                                                                                 4.5.51650                                                                           
Client                                                                               4.0.0.0      

Yes, other hosts are 2017. Issue is only with one 2014

**Comment by potatoqualitee** [comment]
Thank you for helping troubleshoot, @ACALVETT! There is indeed a dependency on .NET 4.6.2, as the newer versions of SMO have bug fixes and new features that we needed and the newer versions require .NET 4.6.2

This is described in https://github.com/dataplat/dbatools/releases/tag/v1.1.0

If you can't upgrade to .NET 4.6.2, you can still use the older version of dbatools we released on July 13, 2021 by running: `Install-Module -Name dbatools -RequiredVersion 1.0.173`

**Comment by potatoqualitee** [comment]
Our manifest actually requires .NEt 4.6.2 but it seems it's not enforced :(

```
    # Minimum version of the .NET Framework required by this module
    DotNetFrameworkVersion = '4.6.2'
```

**Comment by abhishekrnair** [comment]
I tried with version 1.0.173 - but still getting the same error

PS C:\Users\abhishek.nair> Get-Module

ModuleType Version    Name                                ExportedCommands                                                                                                                    
---------- -------    ----                                ----------------                                                                                                                    
Script     1.0.173    dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, Add-DbaAgListener...}                                                     
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                                                 
Manifest   3.1.0.0    Microsoft.Powershell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                                                  
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                           



PS C:\Users\abhishek.nair> Get-DbaDatabase -SqlInstance localhost
WARNING: [07:24:32][Get-DbaDatabase] Error occurred while establishing connection to localhost | Method not found: '!!0[] System.Array.Empty()'.

**Comment by potatoqualitee** [comment]
Wow, interesting. Can you try from a brand new window and see if it's resolved in a new session, @abhishekrnair ? If so, then we'll dig deeper.

**Comment by abhishekrnair** [comment]
Tried that as well, still no luck @potatoqualitee

**Comment by potatoqualitee** [comment]
Mmm, I'm not sure I'll be able to assist as this is an issue that deals with DLLs and that's not my forte. It's not ideal but perhaps downgrade to something like 1.0.100 until someone with better library skills picks this up? @FriedrichWeinmann got any time to take a look, by chance? 🙇🏼

**Comment by abhishekrnair** [comment]
JFYI, I tried 1.0.100 and nothing changed

**Comment by potatoqualitee** [comment]
that's actually good news in a way, it points to a system issue (tho wait, it can be repro'd wth, maybe it's SMO?). can you go back to [0.9.834](https://www.powershellgallery.com/packages/dbatools/0.9.834) and see what happens?

**Comment by abhishekrnair** [comment]
PS C:\Users\abhishek.nair> Import-Module 'C:\Program Files\WindowsPowerShell\Modules\dbatools'
Get-Module

ModuleType Version    Name                                ExportedCommands                                                                                                                    
---------- -------    ----                                ----------------                                                                                                                    
Script     0.9.834    dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, Add-DbaAgListener...}                                                     
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                                                 
Manifest   3.1.0.0    Microsoft.Powershell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                                                  
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                           



PS C:\Users\abhishek.nair> Get-DbaDatabase -SqlInstance localhost
WARNING: [09:53:05][Get-DbaDatabase] Error occurred while establishing connection to localhost | Method not found: '!!0[] System.Array.Empty()'.

PS C:\Users\abhishek.nair>

**Comment by ACALVETT** [comment]
Not sure where to take this but I could repo the original problem but I can not repo using 1.0.173

**Comment by abhishekrnair** [comment]
I am doing offline install - what is the procedure of removing module, is there anything additional steps other replacing the existing folder

**Comment by ACALVETT** [comment]
Replace folder should be enough, you can also do an import-module from another path which is something i do, eg

```
import-module c:\folder\dbatools\dbaTools.psm1
```

**Comment by abhishekrnair** [comment]
PS C:\Users\Administrator> Import-module C:\Temp\dbas\dbatools\dbaTools.psm1

PS C:\Users\Administrator> Get-Module

ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                                                      
---------- -------    ----                                ----------------                                                                                                                                                                                                                      
Script     **0.0**        dbaTools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, Add-DbaAgListener...}                                                                                                                                                       
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                                                                                                                                                   
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                                                                                                                                                    
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                                                                                                                             



PS C:\Users\Administrator> Get-DbaDatabase -SqlInstance localhost
WARNING: [07:47:06][Get-DbaDatabase] Error occurred while establishing connection to localhost | Method not found: '!!0[] System.Array.Empty()'.

PS C:\Users\Administrator>

**Comment by wsmelton** [comment]
Please import using the psd1 and not the psm1 file.

**Comment by alhandra** [comment]
Hi, also reproduced this on windows 2012 r2 with sql 2012

**Comment by potatoqualitee** [comment]
@alhandra can you run this and let us know what it says? i think the answer will be to update .NET to 4.6+

```
gci 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -recurse | gp -name Version -EA 0 | where { $_.PSChildName -match '^(?!S)\p{L}'} | select PSChildName, Version
```

**Comment by andreasjordan** [comment]
Let me close this for now, but we can reopen if needed.
